package devstudioai.android.support

import devstudioai.android.support.tools.AndroidSdk
import devstudioai.android.support.tools.DebugKeystore
import devstudioai.build.BuildGoal
import devstudioai.build.BuildRequest
import devstudioai.build.VariantSelector
import devstudioai.build.engine.BuildCache
import devstudioai.build.engine.SimpleTaskContext
import devstudioai.build.engine.TaskExecutorImpl
import devstudioai.model.BuildSystemId
import devstudioai.model.FacetTemplate
import devstudioai.model.ModuleId
import devstudioai.model.ModuleType
import devstudioai.model.SourceSetTemplate
import devstudioai.model.impl.FacetCodecRegistry
import devstudioai.model.impl.ModuleTypeRegistry
import devstudioai.model.impl.ProjectModel
import devstudioai.platform.PluginId
import devstudioai.platform.impl.PlatformCore
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assumptions.assumeTrue
import java.nio.file.Files
import java.util.zip.ZipFile
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * The Android multi-module sample (`mobile → feature → logic`) generated by [SampleAndroidProject] builds
 * to a real signed APK. This is the Android counterpart to the Java sample's build test, and exercises the
 * whole pipeline on a realistic project: an `android-lib` with its own resource + decoupled `R`, cross-
 * module resource merge, and a transitive plain-Java dependency. Skipped when no Android SDK is installed.
 */
class SampleAndroidProjectTest {

    private object JavaLib : ModuleType {
        override val id = "java-lib"
        override val displayName = "Java Library"
        override fun defaultSourceSets(): List<SourceSetTemplate> = emptyList()
        override fun defaultFacets(): List<FacetTemplate> = emptyList()
        override fun supportedBuildSystems(): Set<BuildSystemId> = setOf(BuildSystemId.NATIVE)
    }

    @Test
    fun theAndroidSampleBuildsToASignedApk() {
        val sdk = AndroidSdk.findSdkRoot()?.let { AndroidSdk.detect(it) }
        assumeTrue(sdk != null && sdk.isComplete(), "Android SDK not installed; skipping")
        sdk!!

        val dir = Files.createTempDirectory("android-sample")
        val platform = PlatformCore()
        try {
            val store = ProjectModel.open(dir, platform, FacetCodecRegistry().register(AndroidFacetCodec))
            val types = ModuleTypeRegistry(platform.extensions)
            types.register(JavaLib, PluginId("java-support"))
            AndroidSupport.register(types, FacetCodecRegistry())

            SampleAndroidProject.generate(store, types.resolve("android-app"), types.resolve("android-lib"), types.resolve("java-lib"))

            val signing = DebugKeystore.getOrCreate(dir.resolve(".keystore/debug.ks"), sdk.keytool)
            val buildSystem = AndroidBuildSystem.inProcess(sdk, signing)
            val project = store.workspace.projects.single { it.name == SampleAndroidProject.PROJECT }
            val graph = buildSystem.createBuildGraph(
                project, BuildRequest(listOf(ModuleId("app")), VariantSelector("debug"), BuildGoal.PACKAGE),
            )
            val log = StringBuilder()
            val outcome = runBlocking {
                TaskExecutorImpl(BuildCache(dir.resolve(".caches/build"))).execute(graph, SimpleTaskContext(log = { log.appendLine(it) }), 2)
            }
            assertTrue(outcome.succeeded, "android sample build failed:\n$log")

            val apk = dir.resolve("app/build/outputs/apk/debug/app-debug.apk")
            ZipFile(apk.toFile()).use { zf ->
                val entries = zf.entries().toList().map { it.name }.toSet()
                assertTrue("classes.dex" in entries && "resources.arsc" in entries, "incomplete APK: $entries")
                // all three modules' code dexed — native multidex splits the layers across classes*.dex.
                val dex = entries.filter { it.matches(Regex("classes\\d*\\.dex")) }
                    .joinToString(" ") { zf.getInputStream(zf.getEntry(it)).readBytes().toString(Charsets.ISO_8859_1) }
                assertTrue("Lcom/example/app/MainActivity;" in dex, "app not dexed")
                assertTrue("Lcom/example/feature/FeatureText;" in dex, "android-lib not dexed")
                assertTrue("Lcom/example/core/Calc;" in dex, "transitive java-lib not dexed")
                val arsc = zf.getInputStream(zf.getEntry("resources.arsc")).readBytes().toString(Charsets.ISO_8859_1)
                assertTrue("feature_title" in arsc && "app_name" in arsc, "resources not merged: arsc")
            }
        } finally {
            platform.dispose(); dir.toFile().deleteRecursively()
        }
    }
}
